car_length: 2.8
car_width: 1.85

initial_pose: [1.0, 5.0, -1.57, 0, 0]
goal_pose: [5.0, 10.0, 1.57, 0, 0]

trajectory_time: 20
Ts: 0.1

state_lowerbound: [-100.0, -100.0, -100, -1.0, -1.0]
state_upperbound: [100.0, 100.0, 100, 1.0, 1.0]
input_lowerbound: [-1.0, -1.0]
input_upperbound: [1.0, 1.0]


state_weight: [0.0, 0.0, 0.0, 0.0, 0.0]
input_weight: [4.0, 4.0]

n_sqp: 50
max_iteration: 100
rho_slack: 1000000.0

